name: Check version/ Send email/ update requirements 
on: workflow_dispatch 

jobs:

  check_versions:

    runs-on: ubuntu-latest

    steps:
    - 
      name: Checkout repository
      uses: actions/checkout@v2
#     - 
#       name: Set up Python
#       run: |
#         eval "$(pyenv init -)"
#         pyenv shell software_benchmarking-3.8
    - 
      name: Run script and save output
      run: |
        pip install outdated
        pip install -r requirements.txt
        output=$(python version_warnign.py)
        output="${output//'%'/'%25'}"
        echo "::set-output name=final_output::$output"
      id: version_check
    -
      name: Check if outdated/Send email
      if: steps.version_check.outputs.final_output == 'True'
      uses: dawidd6/action-send-mail@v1.3.0
      with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL }}
    # Optional (recommended) mail server password:
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Package version check
          to: ${{ secrets.EMAIL }}
          from: Package version check
          secure: true
          body: Some packages are out of date.
    -
      name: Check if outdated/Update txt file
      if: steps.version_check.outputs.final_output == 'True'
      run: |
        echo True
        pip install pyquil --upgrade
        pip install qiskit --upgrade
        pip install pytket --upgrade
        python -m pip freeze > requirements.txt
   
#     - 
#        uses: EndBug/add-and-commit@v7 
#        with:
#           add: 'requirements.txt'
#           author_name: Kris
#           author_email: kristiyan.dilov@cambridgequantum.com
        
#           default_author: github_actor
#           message: 'Just a message' 
#           push: true
    - 
       name: Create Pull Request
       uses: peter-evans/create-pull-request@v3
       with:
            author_name: Kris <kristiyan.dilov@cambridgequantum.com>
            branch: Update_txt_file
            committer: Kris <kristiyan.dilov@cambridgequantum.com>
    - 
       name: Check outputs
       run: |
            echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
            echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
          
    

    - 
      name: Check if upto date/Dont send email
      if: steps.version_check.outputs.final_output != 'True'
      run: echo pyquil is upto date
