name: Version_warning
    
    
on:
     watch:
        types: [ started ]
   
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:

        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
        - run: python version_warning.py
             
