name: run my warning via python
    
 on:
  watch:
    types: [ started ]
   
    
    jobs:
      build:
        runs-on: ubuntu-latest
    
        steps:
          - name: execute py script # run the run.py to get the latest data
            run: |
              python version_warning.py
