name: Activate benchmarks if True


on:
  watch:
    types: [ started ]
    

jobs:

  check_versions:

    runs-on: [self-hosted, macos]

    steps:
    - 
      name: Checkout repository
      uses: actions/checkout@v2
    - 
      name: Set up Python
      run: |
        eval "$(pyenv init -)"
        pyenv shell software_benchmarking-3.8
    - 
      name: Run script and save output
      run: |
        pip install outdated
        pip install -r requirements.txt
        output=$(python version_warning.py)
        output="${output//'%'/'%25'}"
        echo "::set-output name=final_output::$output"
      id: version_check
    -
      name: Check if outdated/ Dispatch/ Send email
      if: steps.version_check.outputs.final_output == 'True'
      uses: dawidd6/action-send-mail@v1.3.0
      with:
      run: |
         curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/github_actions_practise/Send_mail.yml/dispatches --data '{"event_type": "build_application"}'

          

    - 
      name: Check if upto date/Dont send email
      if: steps.version_check.outputs.final_output != 'True'
      run: echo pyquil is upto date
        
          
