name: CI Part 1 Check if True
on: workflow_dispatch 

jobs:

  check_versions:

    runs-on: ubuntu-latest

    steps:
    - 
      name: Checkout repository
      uses: actions/checkout@v2
#     - 
#       name: Set up Python
#       run: |
#         eval "$(pyenv init -)"
#         pyenv shell software_benchmarking-3.8
    - 
      name: Run script and save output
      run: |
        pip install outdated
        pip install -r requirements.txt
        output=$(python version_warnign.py)
        output="${output//'%'/'%25'}"
        echo "::set-output name=final_output::$output"
      id: version_check
    -
      name: Check if outdated/ Dispatch/ Send email
      if: steps.version_check.outputs.final_output == 'True'
      run: |
        echo True
        pip install pyquil --upgrade
        pip install qiskit --upgrade
        pip install pytket --upgrade
        python -m pip freeze > requirements.txt
   
    - 
       uses: EndBug/add-and-commit@v7 # You can change this to use a specific version.
       with:
    # The arguments for the `git add` command (see the paragraph below for more info)
    # Default: '.'
     
          add: 'requirements.txt'
          author_name: Kris
          author_email: kristiyan.dilov@gmail.com
          #branch: some-branch
          default_author: github_actor
          message: 'Just a message'      
          push: true
      #change requirements.txt with 
      #add and commit
      #pull request
    - 
      name: Check if upto date/Dont send email
      if: steps.version_check.outputs.final_output != 'True'
      run: echo False
        
          
