name: CI Part 2 Send email if True
  
on: workflow_dispatch

    
jobs:
  on-success:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
       - name: Checkout code
         uses: actions/checkout@v2
        
       - name: Send email with image
         uses: dawidd6/action-send-mail@v3
         with:
    # Required mail server address:
            server_address: smtp.gmail.com
    # Required mail server port:
            server_port: 465
    # Optional (recommended): mail server username:
            username: ${{ secrets.EMAIL }}
    # Optional (recommended) mail server password:
            password: ${{ secrets.EMAIL_PASSWORD }}
    # Required mail subject:
            subject: Github Actions job result
    # Required recipients' addresses:
            to: ${{ secrets.EMAIL }}
    # Required sender full name (address can be skipped):
            from: Luke Skywalker # <user@example.com>
    # Optional whether this connection use TLS (default is true if server_port is 465)
            secure: true
    # Optional plain body:
            body: Build job of ${{github.repository}} completed successfully!

            attachments: folder/cqc.jpg   
 
