name: Mail on Star

on:
  watch:
    types: [ started ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:

    name: Version_warning
    
  
    runs-on: ubuntu-latest
    
    steps:
      
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
        - name: 'Check_version'
          run: |
            pip install -r requirements.txt
            python version_warnign.py
          
            if [ -z "$(python version_warnign.py)"]; then
            
              echo "::set-output name=push::false"
              echo IS FALSE
 
            else
              
              echo "::set-output name=push::true"
              echo IS TRUE
            
            fi 
          
        - name: ✨ Send email, you star
          if: steps.Check_version.outputs.push == 'true'
          uses: dawidd6/action-send-mail@v1.3.0
          with:
            server_address: smtp.gmail.com
            server_port: 465
            username: kristiyan.dilov@cambridgequantum.com
            password: =[<F8Lza
            subject: Your a star ✨
            body: ${{ github.actor }} If you see this statement, this means that version warning has successfuly ran first inside ${{ github.repository }}
            to: kristiyan.dilov@cambridgequantum.com
            from: kristiyan.dilov@cambridgequantum.com
            attachments: rigetti_python.png

 #
              

      
  #notify:
      #needs: build
  # This workflow contains a single job called "email"
  
    # The type of runner that the job will run on
    #runs-on: ubuntu-latest
    
    #"!contains(github.event.head_commit.message, 'SKIP SCRIPTS')"
    # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#         - name: ✨ Send email, you star
#           uses: dawidd6/action-send-mail@v1.3.0
#           with:
#             server_address: smtp.gmail.com
#             server_port: 465
#             username: kristiyan.dilov@cambridgequantum.com
#             password: =[<F8Lza
#             subject: Your a star ✨
#             body: ${{ github.actor }} If you see this statement, this means that version warning has successfuly ran first inside ${{ github.repository }}
#             to: kristiyan.dilov@cambridgequantum.com
#             from: kristiyan.dilov@cambridgequantum.com
#             attachments: rigetti_python.png
